module.exports = {
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: false,
  singleQuote: true,
  quoteProps: 'as-needed',
  jsxSingleQuote: false,
  trailingComma: 'es5',
  bracketSpacing: true,
  arrowParens: 'always',
  endOfLine: 'auto',
  plugins: [
    require.resolve('@trivago/prettier-plugin-sort-imports'),
    'prettier-plugin-tailwindcss',
  ],
  tailwindFunctions: ['tv'],
  importOrder: [
    '^react$',
    '^next$',
    '^next/(.*)$',
    '^next-themes$',
    '^next-themes/(.*)$',
    '^lucide-react$',
    '^lucide-react/(.*)$',
    '^@/components/(.*)$',
    '^@/lib/(.*)$',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
}
