name: Test

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.13

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test
